import dayjs from 'dayjs';
import type { EmployeeForm, EmployeeSearchForm } from './types';

export const employeeFormDefaultValues: EmployeeForm = {
  imagePath: null,
  employeeId: '',
  genderId: '',
  prefixId: '',
  firstName: '',
  lastName: '',
  nickname: '',
  prefixEnId: '',
  firstNameEn: '',
  lastNameEn: '',
  nicknameEn: '',
  orgStructureId: '',
  dateOfBirth: dayjs().toDate(),
  placementDate: dayjs().toDate(),
  retirementDate: dayjs().toDate(),
  nationalId: '',
  passportNumber: '',
  telephone: '',
  email: '',
  lineId: null,
  fatherFullName: null,
  motherFullName: null,
  motherMaidenName: null,
  maritalStatus: false,
  spouseFullName: null,
  spouseMaidenName: null,
  contactPersonName: '',
  contactPersonTel: '',
  currentHouseNumber: '',
  currentMoo: '',
  currentSoi: '',
  currectYak: '',
  currentRoad: '',
  currentSubdistrict: '',
  currentDistrict: '',
  currentProvinceId: '',
  currentPostcode: '',
  permanentHouseNumber: '',
  permanentMoo: '',
  permanentSoi: '',
  permanentYak: '',
  permanentRoad: '',
  permanentSubdistrict: '',
  permanentDistrict: '',
  permanentProvinceId: '',
  permanentPostcode: '',
  note: null,
  id: '',
};

export const employeeSearchFormDefaultValues: EmployeeSearchForm = {
  employeeId: null,
  genderId: null,
  firstName: null,
  lastName: null,
  nickname: null,
  firstNameEn: null,
  lastNameEn: null,
  nicknameEn: null,
  email: null,
  lineId: null,
};

export const defaultPagination = {
  pageIndex: 1,
  pageSize: 10,
};
