import { FooterLinks } from 'apps/web-next/src/components/footer/footer';
import { HeaderMegaMenu } from 'apps/web-next/src/components/header/header';
import '../styles/global.scss';
import Providers from './providers';

export const metadata = {
  title: 'Welcome to web-next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <HeaderMegaMenu />
          {children}
          <FooterLinks />
        </Providers>
      </body>
    </html>
  );
}
